config/routes.rb
Members::Application.routes.draw do
  resources :members

  get "home/index"

root :to => 'members#index'

resources :roles

end

app/models/member.rb
class Member < ActiveRecord::Base
  attr_accessible :birthday, :email, :name, :phone, :role_id, :street, :zip, :first_name, :city

  validates :email, :uniqueness => true
  validates :name, :presence => true, :length => {:maximum => 60}
  validates :first_name, :presence => true, :length => {:maximum => 60}
  validates :role_id, :presence => true

  belongs_to :role
end

app/models/role.rb
class Role < ActiveRecord::Base
  attr_accessible :active, :fee, :name
  validates :name, :presence => true
  validates :fee, :numericality => true, :presence => true

  has_many :members
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController

  # Get all roles
  def get_roles
    @roles = Role.all
  end

  # GET /members
  # GET /members.json
  def index
    @members = Member.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @members }
    end
  end

  # GET /members/1
  # GET /members/1.json
  def show
    @member = Member.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @member }
      format.xml { render xml: @member }
    end
  end

  # GET /members/new
  # GET /members/new.json
  def new
    @member = Member.new
    get_roles

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @member }
    end
  end

  # GET /members/1/edit
  def edit
    @member = Member.find(params[:id])
    get_roles
  end

  # POST /members
  # POST /members.json
  def create
    @member = Member.new(params[:member])

    respond_to do |format|
      if @member.save
        format.html { redirect_to @member, notice: 'Member was successfully created.' }
        format.json { render json: @member, status: :created, location: @member }
      else
        format.html { render action: "new" }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /members/1
  # PUT /members/1.json
  def update
    @member = Member.find(params[:id])

    respond_to do |format|
      if @member.update_attributes(params[:member])
        format.html { redirect_to @member, notice: 'Member was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /members/1
  # DELETE /members/1.json
  def destroy
    @member = Member.find(params[:id])
    @member.destroy

    respond_to do |format|
      format.html { redirect_to members_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  def index
    @roles = Role.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @roles }
    end
  end

  # GET /members/1
  # GET /members/1.json
  def show
    @role = Role.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @role }
    end
  end

  # GET /members/new
  # GET /members/new.json
  def new
    @role = Role.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @role }
    end
  end

  # GET /members/1/edit
  def edit
    @role = Role.find(params[:id])
  end

  # POST /members
  # POST /members.json
  def create
    @role = Role.new(params[:role])

    respond_to do |format|
      if @role.save
        format.html { redirect_to @role, notice: 'Role was successfully created.' }
        format.json { render json: @role, status: :created, location: @role }
      else
        format.html { render action: "new" }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /members/1
  # PUT /members/1.json
  def update
    @role = Role.find(params[:id])

    respond_to do |format|
      if @role.update_attributes(params[:role])
        format.html { redirect_to @role, notice: 'Role was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /members/1
  # DELETE /members/1.json
  def destroy
    @role = Role.find(params[:id])
    @role.destroy

    respond_to do |format|
      format.html { redirect_to roles_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # @param [Datetime] birthday
  def age(birthday)
    now = Time.now.utc.to_date
    now.year - birthday.year - (birthday.to_date.change(:year => now.year) > now ? 1 : 0)
  end

  def nav_link_to(link_text, link_path)
    class_name = current_page?(link_path) ? 'active' : ''

    content_tag(:li, :class => class_name) do
      link_to link_text, link_path
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/roles_helper.rb
module RolesHelper
  # set_check provides the icon according to the roles activity status
  def set_check(getrole)
    getrole ? 'icon-ok' : 'icon-remove'
  end
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Members</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render :partial => "shared/nav" %>
<div class="container-fluid">
  <div class="row-fluid">
    <div class="span12">
      <%= yield %>
    </div>
  </div>
</div>
</body>
</html>

app/views/members/_form.html.erb
<%= simple_form_for(@member, :html => { :class => 'form-horizontal' }, :defaults => { :input_html => { :class => 'span4' } }) do |f| %>
  <% if @member.errors.any? %>
    <div class="alert alert-error" id="error_explanation">
      <h2><%= pluralize(@member.errors.count, "error") %> prohibited this type from being saved:</h2>

      <ul>
        <% @member.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.input :name, :label => 'Name', :placeholder => 'Nachname' %>
  </div>
    <div class="field">
      <%= f.input :first_name, :label => 'Vorname', :placeholder => 'Vorname' %>
    </div>
  <div class="field">
    <%= f.input :street, :label => 'Straße', :placeholder => 'Straße' %>
  </div>
  <div class="field">
    <%= f.input :zip, :label => 'Postleitzahl', :placeholder => 'PLZ' %>
  </div>
    <div class="field">
      <%= f.input :city, :label => 'Ort', :placeholder => 'Ort' %>
    </div>
  <div class="field">
    <%= f.input :phone, :label=> 'Telefon', :placeholder => 'Telefon' %>
  </div>
  <div class="field">
    <%= f.input :email, :label => 'E-Mail', :placeholder => 'mail@server.com' %>
  </div>
  <div class="field">
    <%= f.input :birthday, :as => :date, :start_year => Date.today.year - 90,
                :end_year => Date.today.year - 1, :discard_day => false,
                :order => [:day, :month, :year], :label => 'Geburtstag', :input_html => { :class => '' } %>
  </div>
  <div class="field">
    <%= f.association :role, :label => 'Mitgliedstyp', :prompt => "Bitte Mitgliedstyp auswählen" %>
  </div>
  <div class="actions">
    <%= f.submit 'Speichern', :class => 'btn' %>
  </div>
<% end %>

app/views/members/edit.html.erb
<h1>Mitglied bearbeiten</h1>

<%= render 'form' %>

<%= link_to 'Show', @member %> |
<%= link_to 'Back', members_path %>

app/views/members/index.html.erb
<h1>Mitgliederliste</h1>

<table class="table">
  <tr>
    <th>Name</th>
    <th>Vorname</th>
    <th>Straße</th>
    <th>PLZ</th>
    <th>Ort</th>
    <th>Telefon</th>
    <th>Email</th>
    <th>Geburtstag</th>
    <th>Alter</th>
    <th>Typ</th>
    <th>Aktionen</th>
  </tr>

<% @members.each do |member|
%>
  <tr>
    <td><%= member.name %></td>
    <td><%= member.first_name %></td>
    <td><%= member.street %></td>
    <td><%= member.zip %></td>
    <td><%= member.city %></td>
    <td><%= member.phone %></td>
    <td><%= member.email %></td>
    <td><%= member.birthday.strftime("%d. %b %Y") %></td>
    <td><%= age(member.birthday)  %></td>
    <td><%= member.role.name %></td>
    <td><div class="btn-group">
      <% # Bootstrap-Button-Gruppe festlegen, mit Funktionalität %>
      <%= link_to(content_tag(:i, nil, :class=>"icon-search"), member, :class => "btn")  %>
      <%= link_to(content_tag(:i, nil, :class=>"icon-pencil"), edit_member_path(member), :class => "btn")  %>
      <%= link_to(content_tag(:i, nil, :class => "icon-trash"), member, method: :delete, data: { confirm: 'Sind Sie sicher?' }, :class => "btn") %>
    </div></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Neues Mitglied', new_member_path, :class => "btn btn-primary" %>

app/views/members/new.html.erb
<h1>Neues Mitglied</h1>

<%= render 'form' %>

<%= link_to 'Zurück', members_path %>

app/views/members/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @member.name %>
</p>

<p>
  <b>Vorname:</b>
  <%= @member.first_name %>
</p>

<p>
  <b>Straße:</b>
  <%= @member.street %>
</p>

<p>
  <b>PLZ:</b>
  <%= @member.zip %>
</p>

<p>
  <b>Ort:</b>
  <%= @member.city %>
</p>

<p>
  <b>Telefon:</b>
  <%= @member.phone %>
</p>

<p>
  <b>Email:</b>
  <%= @member.email %>
</p>

<p>
  <b>Geburtstag:</b>
  <%= @member.birthday.strftime("%d. %B %Y") %>
</p>

<p>
  <b>Alter:</b>
  <%= age(@member.birthday) %>
</p>

<p>
  <b>Status:</b>
  <%= @member.role_id %>
</p>


<%= link_to 'Bearbeiten', edit_member_path(@member) %> |
<%= link_to 'Zurück', members_path %>

app/views/roles/_form.html.erb
<%= simple_form_for(@role, :html => { :class => 'form-horizontal' }, :defaults => { :input_html => { :class => 'span4' } }) do |f| %>
    <% if @role.errors.any? %>
        <div class="alert alert-error" id="error_explanation">
          <h2><%= pluralize(@role.errors.count, "error") %> prohibited this type from being saved:</h2>

          <ul>
            <% @role.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.input :name, :label => 'Bezeichnung', :placeholder => 'Bezeichnung' %>
    </div>
    <div class="field">
      <%= f.input :fee, :label => 'Gebühr', :placeholder => 'Mitgliedsbeitrag' %>
    </div>
    <div class="field">
      <%= f.input :active, :as => :boolean, :label => 'Aktiv', :input_html => { :class => 'checkbox' } %>
    </div>
    <div class="actions">
      <%= f.submit 'Speichern', :class => 'btn' %>
    </div>
<% end %>

app/views/roles/edit.html.erb
<h1>Mitgliedstyp bearbeiten</h1>

<%= render 'form' %>

<%= link_to 'Show', @role %> |
<%= link_to 'Back', role_path %>

app/views/roles/index.html.erb
<h1>Mitgliedstypen</h1>

<table class="table">
  <tr>
    <th>Bezeichnung</th>
    <th>Aktiv</th>
    <th>Gebühr</th>
    <th>Aktionen</th>
  </tr>
  <% @roles.each do |role| %>
      <tr>
        <td><%= role.name %></td>
        <td><%= content_tag(:i, '', :class => set_check(role.active)) %></td>
        <td>€ <%= role.fee %></td>
        <td><div class="btn-group">
          <% # Bootstrap-Button-Gruppe festlegen, mit Funktionalität %>
          <%= link_to(content_tag(:i, nil, :class=>"icon-search"), role, :class => "btn")  %>
          <%= link_to(content_tag(:i, nil, :class=>"icon-pencil"), edit_role_path(role), :class => "btn")  %>
          <%= link_to(content_tag(:i, nil, :class => "icon-trash"), role, method: :delete, data: { confirm: 'Sind Sie sicher?' }, :class => "btn") %>
        </div></td>
      </tr>
  <% end %>
  <% if @roles.empty? %>
      <tr>
        <td colspan="4">Keine Rollen eingetragen!</td>
      </tr>
  <% end %>
</table>

<br />

<%= link_to 'Neuer Typ', new_role_path, :class => "btn btn-primary" %>

app/views/roles/new.html.erb
<h1>Neuer Mitgliedstyp</h1>

<%= render 'form' %>

<%= link_to 'Zurück', roles_path %>

app/views/roles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Bezeichnung:</b>
  <%= @role.name %>
</p>

<p>
  <b>Aktiv:</b>
  <%= content_tag(:i, '', :class => set_check(@role.active)) %>
</p>

<p>
  <b>Gebühr:</b>
  € <%= @role.fee %>
</p>

<%= link_to 'Bearbeiten', edit_role_path(@role) %> |
<%= link_to 'Zurück', roles_path %>

app/views/shared/_nav.html.erb
<div class="navbar navbar-inverse fixed top">
  <div class="navbar-inner">
    <%=  link_to "Mitgliederverwaltung", members_path, :class => 'brand'  %>
    <ul class="nav">
      <%= nav_link_to 'Mitglieder', members_path %>
      <%= nav_link_to 'Mitgliedstypen', roles_path %>
    </ul>
  </div>
</div>